// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Roman Tumaykin")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2017 Roman Tumaykin")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("1.2.0.0")]
[assembly: AssemblyFileVersionAttribute("1.2.0.0")]
