// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Roman Tumaykin")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2017 Roman Tumaykin")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyVersionAttribute("2.3.0.0")]
[assembly: AssemblyFileVersionAttribute("2.3.0.0")]
